---
title: "Research"
listing: projects
toc: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Research

### Peer-Reviewed Journal Articles

* **Saxena, K.**, & Ofori-Parku, S. S. (2024). ‘Funny’ Politics: Stand-up Political Comedy, Public Engagement, Critical Thinking, and Opinion Sharing in India. Journal of Creative Communications, 0(0). https://doi.org/10.1177/09732586241252201

* **Saxena, K.** & Martinez, G. (2024) Collaborative Film Making for Socio-political Transformation in Colombia: A Decolonial Perspective. Jump Cut: A Review of Contemporary Media, Issue 62. https://www.ejumpcut.org/currentissue/Saxena-Martinez/index.html

* **Saxena, K.** (2023). That’s a ‘Sign’!: How Placards Communicated Disapproval of the Citizenship Amendment Act (CAA) in India. Communication Studies, 1–15. https://doi.org/10.1080/10510974.2023.2210631

* Markowitz, D. M., Blackburn, K. G., **Saxena, K.**, Marion, J., Olivarez, O., Hernandez, R., Woodworth, M. T., & Hancock, J. T. (2022). The Truth Project. Journal of Language and Social Psychology, 41(4), 450–461. https://doi.org/10.1177/0261927X211067821

* Martinez, G., & **Saxena, K.** (2021). Mapping the promises and perils of distance education during the COVID-19 pandemic: Peru’s case. Jump Cut: A Review of Contemporary Media, Issue 60. https://www.ejumpcut.org/archive/jc60.2021/MartinezSaxena-PeruEducation/index.html

### Book Reviews
* **Saxena, K.** (2024). Cracking up: Black feminist comedy in the twentieth & twenty-first century United States: by Katelyn Hale Wood, United States, University of Iowa Press, 2021, 204 pp., $28.91 (paperback), ISBN 9781609387723. Critical Studies in Media Communication, 1–3. https://doi.org/10.1080/15295036.2024.2371127

* **Saxena, K.** (Forthcoming) Radio for the Millions: Hindi-Urdu Broadcasting Across Borders, by Huacuja Alonso. Columbia University Press. The Global South

### Book Chapter
* **Saxena, K.** & Martinez, G. (accepted with revisions). Women of Medellin's Comuna 13 and Documentary Film Teachers: Re-claiming Personal Stories and Narratives for Social Change. Chapter for an edited volume Documentary Film in Latin America and the Caribbean: Perspectives and Practice


### PEER-REVIEWED CONFERENCES PRESENTATIONS

* **Saxena, K.** (2024) ‘Funny’ Resistance: Stand-up Comedy for Socio-political Activism in India. Paper presented at the International Communication Association (ICA) Conference, Gold Coast.

* **Saxena, K.**, (2023) Stand-up Comedy for Political Resistance in India. Presented and chaired the panel ‘Activism in and through Media Industry' at the International Communication Association (ICA) Conference, Toronto.
Among top three student papers in the Activism, Communication and Social Justice Division

* **Saxena, K.**, (2022) 'Laughing' at Gender Based Violence: Talking About Marital Rape Through Stand-up Comedy in India. Paper presented at the International Communication Association (ICA) Conference, Paris.

* Clark, K., **Saxena, K.**, Shafer, A., & Beyene, G. (2022) Understanding Gendered Beliefs, Barriers, and Opportunities in Condom Communication. Paper presented at the International Communication Association (ICA) Conference, Paris.

* **Saxena, K.**, & Ofori-Parku, S. (2021) ‘Funny’ Politics: Effects of Stand-Up Comedy on Public Engagement, Critical Thinking and Opinion Sharing. Paper presented at the International Association for Media and Communication Research (IAMCR), Nairobi.

* **Saxena. K.** (2020) ‘Telling Everyone’ the Media Narrative of the United Nations Sustainable Development Goals: Are They Reaching Everyone? Paper presented at the Annual What is Information Media Virtual Conference, Eugene.

* **Saxena, K.** (2017) The Role of Mobile Phones in Empowerment of Female Domestic Workers. Paper presented at the What is Life Conference Annual Media Conference, Portland.
